version: "3"

services:

    #mysql
    mysql:
      image: mysql:5.7.22
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: ${DB_DATABASE:-admin}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
        MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
        MYSQL_USER: ${DB_USERNAME:-username}
      volumes:
        - ./.docker/mysql/dbdata:/var/lib/mysql
      ports:
        - "4022:3306"
      networks:
        - mysql

networks:
  mysql:
    driver: bridge
